param([string]$RootDir = "E:\gym\abcv-main\abcv-main")

$replacements = @(
    @{rel="404.html"; old='The page you\'"'"'re looking for doesn\'"'"'t exist at GymTranning. Browse our library of science-based workout guides, training plans, and nutrition tools to find what you need.'; new='Page not found at GymTranning. Browse science-based workout guides, training plans, and nutrition tools to find what you need.'}
    @{rel="about.html"; old='GymTranning provides evidence-based workout plans, nutrition guides, and interactive calculators. Discover our mission to make fitness science accessible to all.'; new='GymTranning offers evidence-based workout plans, nutrition guides, and interactive calculators. Our mission: make fitness science accessible to all.'}
    @{rel="accessibility.html"; old='GymTranning is committed to digital accessibility. Learn about our WCAG 2.1 compliance, accessibility features, screen reader support, and keyboard navigation options.'; new='GymTranning is committed to digital accessibility with WCAG 2.1 compliance, screen reader support, and keyboard navigation.'}
    @{rel="affiliate-disclosure.html"; old='GymTranning affiliate disclosure: Learn about our affiliate relationships, how we earn commissions, and our commitment to honest, unbiased product recommendations.'; new='GymTranning affiliate disclosure: Learn about our affiliate relationships, how we earn commissions, and our commitment to unbiased recommendations.'}
    @{rel="blog.html"; old='Explore GymTranning\'"'"'s expert fitness blog with science-based guides on training, nutrition, recovery, and mindset. Evidence-backed articles to transform your physique.'; new="Browse GymTranning's expert fitness blog with science-based guides on training, nutrition, recovery, and mindset. Evidence-backed articles."}
    @{rel="editorial-policy.html"; old='GymTranning editorial policy: Our commitment to evidence-based, accurate fitness content. Learn about our writing standards, review process, and fact-checking procedures.'; new='GymTranning editorial policy: Evidence-based, accurate fitness content. Learn about our writing standards, review process, and fact-checking.'}
    @{rel="blog/advanced-back-isolation.html"; old='Target every muscle of your back with advanced isolation techniques. Cable pullovers, straight-arm pulldowns, and rear delt flyes for complete 3D back development.'; new='Target every back muscle with advanced isolation techniques. Cable pullovers, straight-arm pulldowns, and rear delt flyes for 3D back development.'}
    @{rel="blog/correcting-posture-exercises.html"; old='Fix forward head posture, rounded shoulders, and tech neck with our science-based 3-step protocol. Release tight muscles, mobilize joints, and strengthen weak patterns.'; new='Fix forward head posture, rounded shoulders, and tech neck with our science-based 3-step protocol: release, mobilize, and strengthen.'}
    @{rel="blog/ultimate-guide-fat-loss-part-13.html"; old='Fat loss thermodynamics explained simply. Learn how calories in vs calories out works, why metabolic adaptation happens, and how to apply energy balance science for fat loss.'; new='Fat loss thermodynamics explained simply. Learn how calories in vs calories out works, metabolic adaptation, and energy balance science.'}
    @{rel="blog/ultimate-guide-fat-loss-part-28.html"; old='Create a sustainable calorie deficit for lasting fat loss. Learn the exact deficit size, protein targets, and adjustment strategies to lose fat without losing muscle.'; new='Create a sustainable calorie deficit for lasting fat loss. Learn the exact deficit size, protein targets, and adjustment strategies.'}
    @{rel="blog/ultimate-guide-fat-loss-part-37.html"; old='Optimal macro distribution for fat loss while preserving muscle. Learn exact protein, carb, and fat ratios for cutting based on your body type and training schedule.'; new='Optimal macro distribution for fat loss while preserving muscle. Learn protein, carb, and fat ratios for cutting.'}
    @{rel="blog/ultimate-guide-fat-loss-part-40.html"; old='Control hunger and cravings while dieting. Learn how ghrelin, leptin, and GLP-1 affect appetite and practical strategies to manage hunger during a calorie deficit.'; new='Control hunger and cravings while dieting. Learn how ghrelin, leptin, and GLP-1 affect appetite to manage your deficit.'}
    @{rel="blog/ultimate-guide-fat-loss-part-49.html"; old='Track fat loss progress accurately with multiple methods. Learn how to use the scale, body measurements, progress photos, and strength levels together for reliable tracking.'; new='Track fat loss progress with multiple methods. Use the scale, body measurements, progress photos, and strength levels together.'}
    @{rel="blog/ultimate-guide-fat-loss-part-56.html"; old='Resistance training during a calorie deficit preserves muscle and maximizes fat loss. Learn the best training approach for cutting, including intensity, volume, and recovery.'; new='Resistance training during a calorie deficit preserves muscle and maximizes fat loss. Learn the best cutting approach.'}
    @{rel="blog/ultimate-guide-fat-loss-part-57.html"; old='Use cardio as a fat loss tool the right way. Compare HIIT vs LISS, learn optimal frequency and duration, and get a weekly periodization template for maximum results.'; new='Use cardio as a fat loss tool the right way. Compare HIIT vs LISS and learn optimal frequency and duration for results.'}
    @{rel="blog/ultimate-guide-fat-loss-part-71.html"; old='Systematic NEAT optimization protocol for fat loss. Learn how to track, maintain, and increase non-exercise activity thermogenesis with a step-by-step framework.'; new='Systematic NEAT optimization protocol for fat loss. Track, maintain, and increase non-exercise activity thermogenesis step-by-step.'}
    @{rel="blog/ultimate-guide-fat-loss-part-97.html"; old='Learn exactly how to calculate your fat loss calorie deficit. Step-by-step math from BMR to TDEE to deficit target, with adjustment protocols and real-world examples.'; new='Calculate your fat loss calorie deficit step-by-step. BMR to TDEE to deficit target with adjustment protocols and examples.'}
    @{rel="blog/ultimate-guide-flexibility-part-41.html"; old='Loosen a stiff lower back with targeted mobility exercises. Learn cat-cow, bird-dog, and foam rolling techniques to relieve lumbar stiffness and improve spinal health.'; new='Loosen a stiff lower back with targeted mobility exercises. Cat-cow, bird-dog, and foam rolling for lumbar stiffness relief.'}
    @{rel="blog/ultimate-guide-flexibility-part-50.html"; old='Improve thoracic spine mobility and shoulder range of motion with targeted exercises. Fix rounded back posture, open your chest, and lift heavier with better form.'; new='Improve thoracic spine mobility and shoulder range of motion. Fix rounded back posture, open your chest, and lift heavier.'}
    @{rel="blog/ultimate-guide-flexibility-part-73.html"; old='Master foam rolling for faster recovery and better mobility. Learn proper self-myofascial release techniques for every major muscle group with science-backed protocols.'; new='Master foam rolling for faster recovery. Learn self-myofascial release techniques for every major muscle group.'}
    @{rel="blog/ultimate-guide-home-workouts-part-6.html"; old='Build strength with bodyweight training. Learn calisthenics leverage principles, how to progressively overload without weights, and structure effective home workouts.'; new='Build strength with bodyweight training. Learn calisthenics leverage, progressive overload without weights, and home workouts.'}
    @{rel="blog/ultimate-guide-home-workouts-part-45.html"; old='Build strong legs at home without weights. Learn bodyweight leg exercises, unilateral loading, pistol squat progressions, and home leg programming for size and strength.'; new='Build strong legs at home without weights. Bodyweight leg exercises, pistol squat progressions, and full home leg programming.'}
    @{rel="blog/ultimate-guide-home-workouts-part-53.html"; old='Resistance bands are the most versatile home gym tool. Learn how to choose bands, use them for every muscle group, and program full-body band workouts for strength.'; new='Resistance bands: the most versatile home gym tool. Choose bands, train every muscle, and program full-body workouts.'}
    @{rel="blog/ultimate-guide-home-workouts-part-93.html"; old='Burn fat and build endurance with metabolic conditioning circuits at home. Learn how to structure HIIT, choose exercises, and program home conditioning workouts.'; new='Burn fat and build endurance with metabolic conditioning at home. Structure HIIT and program home conditioning workouts.'}
    @{rel="blog/ultimate-guide-mindset-part-4.html"; old='Motivation fades - discipline lasts. Learn why habits beat willpower for fitness success, how to build automatic routines, and when to use motivation strategically.'; new='Motivation fades\u2014discipline lasts. Learn why habits beat willpower for fitness success and how to build automatic routines.'}
    @{rel="blog/ultimate-guide-mindset-part-7.html"; old='Set SMART fitness goals and build micro-habits that stick. Learn how to create specific, measurable targets and tiny daily actions that compound into big results.'; new='Set SMART fitness goals and build micro-habits that stick. Create specific targets and tiny daily actions that compound.'}
    @{rel="blog/ultimate-guide-mindset-part-18.html"; old='Stop letting friction and excuses kill your workouts. Learn how to identify training barriers, eliminate decision fatigue, and build unbreakable workout consistency.'; new='Stop letting friction and excuses kill your workouts. Identify barriers, eliminate decision fatigue, and build consistency.'}
    @{rel="blog/ultimate-guide-mindset-part-44.html"; old='Never let travel or setbacks derail your fitness. Learn contingency planning for hotel workouts, illness recovery protocols, and how to maintain gains while away from home.'; new='Never let travel or setbacks derail your fitness. Contingency planning for hotel workouts and maintaining gains away from home.'}
    @{rel="blog/ultimate-guide-mindset-part-46.html"; old='Gym anxiety is common but conquerable. Learn practical strategies to overcome fear of judgment, build confidence in the weight room, and train comfortably from day one.'; new='Gym anxiety is common but conquerable. Overcome fear of judgment, build confidence in the weight room, and train comfortably.'}
    @{rel="blog/ultimate-guide-mindset-part-52.html"; old='Train smarter with autoregulation using RIR and RPE. Learn how to adjust training intensity daily based on readiness, fatigue, and performance for maximum gains.'; new='Train smarter with autoregulation using RIR and RPE. Adjust training intensity daily based on readiness and fatigue.'}
    @{rel="blog/ultimate-guide-mindset-part-54.html"; old='Use visual consistency tracking to build unbreakable fitness habits. Learn calendar marking, habit chains, progress charts, and accountability systems that work.'; new='Use visual consistency tracking to build unbreakable fitness habits. Calendar marking and habit chains that work.'}
    @{rel="blog/ultimate-guide-mindset-part-55.html"; old='Central nervous system fatigue is the hidden cause of training plateaus. Learn how to manage CNS stress, recognize overtraining signs, and optimize recovery for strength.'; new='Central nervous system fatigue: the hidden cause of training plateaus. Manage CNS stress and optimize recovery for strength.'}
    @{rel="blog/ultimate-guide-mindset-part-72.html"; old='Build a champion mindset for lifelong fitness success. Learn how elite athletes think, develop mental resilience, and integrate fitness as a permanent lifestyle habit.'; new='Build a champion mindset for lifelong fitness success. Learn how elite athletes think and develop mental resilience.'}
    @{rel="blog/ultimate-guide-mindset-part-88.html"; old='Motivation gets you started - systems keep you going. Learn why habit-based training outperforms willpower and how to design your environment for automatic fitness success.'; new='Motivation gets you started\u2014systems keep you going. Habit-based training outperforms willpower. Design your environment for success.'}
    @{rel="blog/ultimate-guide-mindset-part-94.html"; old='Combine SMART goal setting with micro-habits for unstoppable fitness progress. Learn how to set specific targets and build tiny habits that compound into big results.'; new='Combine SMART goal setting with micro-habits for unstoppable progress. Set specific targets that compound into big results.'}
    @{rel="blog/ultimate-guide-mindset-part-95.html"; old='Stop letting friction and excuses derail your training. Learn how to identify your specific barriers, design your environment for automatic action, and build bulletproof consistency.'; new='Stop letting friction and excuses derail your training. Identify barriers, design your environment, and build bulletproof consistency.'}
    @{rel="blog/ultimate-guide-mindset-part-99.html"; old='Master the mind-muscle connection for accelerated muscle growth. Learn advanced techniques, exercise-specific cues, and how to use neural drive to maximize every rep.'; new='Master the mind-muscle connection for accelerated growth. Advanced techniques and neural drive to maximize every rep.'}
    @{rel="blog/ultimate-guide-muscle-gain-part-60.html"; old='Should you train to failure on every set? Learn how rep ranges, proximity to failure, and load management impact hypertrophy and how to periodize intensity for maximum growth.'; new='Should you train to failure on every set? Learn how proximity to failure and load management impact hypertrophy.'}
    @{rel="blog/ultimate-guide-muscle-gain-part-62.html"; old='Mechanical tension is the primary driver of hypertrophy. Learn how to maximize muscle tension with tempo control, load selection, and mind-muscle connection for better gains.'; new='Mechanical tension is the primary driver of hypertrophy. Maximize muscle tension with tempo, load, and mind-muscle connection.'}
    @{rel="blog/ultimate-guide-muscle-gain-part-83.html"; old='Hardgainers need specific strategies to build muscle. Learn calorie surplus targets, volume requirements, exercise selection, and programming tweaks for results.'; new='Hardgainers need specific strategies to build muscle. Calorie surplus targets, volume requirements, and programming tweaks.'}
    @{rel="blog/ultimate-guide-muscle-gain-part-96.html"; old='Muscle growth is driven by three primary mechanisms. Learn how mechanical tension, muscle damage, and metabolic stress stimulate hypertrophy and how to apply each.'; new='Muscle growth is driven by three mechanisms. How mechanical tension, muscle damage, and metabolic stress stimulate hypertrophy.'}
    @{rel="blog/ultimate-guide-recovery-part-59.html"; old='Central nervous system fatigue is the hidden cause of training plateaus. Learn to identify CNS exhaustion signs and use recovery strategies to reset your nervous system.'; new='Central nervous system fatigue is the hidden cause of plateaus. Identify CNS exhaustion and use recovery strategies to reset.'}
    @{rel="blog/ultimate-guide-recovery-part-86.html"; old='Plan effective deload weeks to maximize long-term progress. Learn when to deload, how to reduce volume, and return stronger than before with science-backed protocols.'; new='Plan effective deload weeks for long-term progress. Learn when to deload, reduce volume, and return stronger.'}
    @{rel="blog/ultimate-guide-strength-training-part-2.html"; old='Strength is a neurological skill before it\'"'"'s a physical one. Learn how neuromuscular adaptation drives early strength gains and how to optimize neural drive for faster results.'; new='Strength is a neurological skill. Learn how neuromuscular adaptation drives early gains and how to optimize neural drive.'}
    @{rel="blog/ultimate-guide-strength-training-part-14.html"; old='Master the squat with proper technique, bracing, and programming. Learn bar position, depth cues, hip hinge mechanics, and how to add 50lbs to your squat safely.'; new='Master the squat with proper technique, bracing, and programming. Bar position, depth cues, and hip hinge mechanics.'}
    @{rel="blog/ultimate-guide-strength-training-part-48.html"; old='Master the Valsalva maneuver for safer, heavier lifts. Learn proper core bracing, intra-abdominal pressure, and when this technique should and should not be used.'; new='Master the Valsalva maneuver for safer, heavier lifts. Proper core bracing and intra-abdominal pressure technique.'}
    @{rel="blog/ultimate-guide-strength-training-part-100.html"; old='Strength is a neurological skill. Learn how your nervous system adapts to heavy lifting, recruits motor units, and drives rapid early strength gains before muscle growth.'; new='Strength is a neurological skill. Your nervous system adapts to heavy lifting and drives early strength gains.'}
)

Write-Host "=== Rewriting too-long meta descriptions ==="
$fixed = 0
$errors = @()
foreach ($r in $replacements) {
    $fullPath = Join-Path $RootDir $r.rel
    if (-not (Test-Path $fullPath)) {
        $errors += "$($r.rel): FILE NOT FOUND"
        continue
    }
    $content = Get-Content -LiteralPath $fullPath -Raw
    $oldStr = $r.old
    $newStr = $r.new
    if ($content -match [regex]::Escape($oldStr)) {
        $content = $content -replace [regex]::Escape($oldStr), $newStr
        Set-Content -LiteralPath $fullPath -Value $content -NoNewline
        $charsIn = $oldStr.Length
        $charsOut = $newStr.Length
        Write-Host "$($r.rel) : $charsIn -> $charsOut chars (saved $($charsIn - $charsOut))"
        $fixed++
    } else {
        $errors += "$($r.rel): OLD STRING NOT FOUND"
    }
}

Write-Host ""
Write-Host "=== Summary ==="
Write-Host "Descriptions rewritten: $fixed"
if ($errors.Count -gt 0) {
    Write-Host "Errors ($($errors.Count)):"
    foreach ($e in $errors) { Write-Host "  $e" }
}
Write-Host "Done."
